create table if not exists public.reports (
  id text primary key,
  created_at bigint not null,
  updated_at bigint not null,
  report_date date not null,
  owner text not null,
  client text not null,
  branch_name text,
  type text not null check (type in ('신규', '매출증대')),
  product text not null check (product in ('3제+클로르', '3제', '클로르')),
  amount numeric not null default 0,
  collection_year integer,
  collection_month integer check (collection_month between 1 and 12),
  prescription_done boolean not null default false
);

alter table public.reports
  add column if not exists prescription_done boolean not null default false;

alter table public.reports
  add column if not exists collection_year integer;

alter table public.reports
  add column if not exists collection_month integer check (collection_month between 1 and 12);

alter table public.reports
  add column if not exists branch_name text;

create index if not exists reports_report_date_idx on public.reports (report_date);
create index if not exists reports_owner_idx on public.reports (owner);
create index if not exists reports_collection_idx on public.reports (collection_year, collection_month);

create table if not exists public.report_logs (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('update', 'delete')),
  created_at bigint not null,
  actor text,
  report_id text,
  client text,
  before_data jsonb,
  after_data jsonb
);

create index if not exists report_logs_created_at_idx on public.report_logs (created_at desc);
create index if not exists report_logs_report_id_idx on public.report_logs (report_id);

create table if not exists public.daily_completions (
  id text primary key,
  report_date date not null,
  owner text not null,
  completed_at bigint not null,
  status text not null default 'done'
);

alter table public.daily_completions
  add column if not exists status text not null default 'done';

create unique index if not exists daily_completions_date_owner_uidx
on public.daily_completions (report_date, owner);

create index if not exists daily_completions_report_date_idx
on public.daily_completions (report_date);

create table if not exists public.team_calendar_days (
  id text primary key,
  calendar_date date not null unique,
  status text not null check (status in ('holiday', 'workday')),
  label text,
  created_at bigint not null,
  updated_at bigint not null
);

create unique index if not exists team_calendar_days_date_uidx
on public.team_calendar_days (calendar_date);

create index if not exists team_calendar_days_status_idx
on public.team_calendar_days (status);

select pg_notify('pgrst', 'reload schema');
