create table if not exists public.reports (
  id text primary key,
  created_at bigint not null,
  updated_at bigint not null,
  report_date date not null,
  owner text not null,
  client text not null,
  branch_name text,
  type text not null check (type in ('신규', '매출증대')),
  product text not null check (product in ('3제+클로르', '3제', '클로르')),
  amount numeric not null default 0,
  collection_year integer,
  collection_month integer check (collection_month between 1 and 12),
  prescription_done boolean not null default false,
  success_case text
);

alter table public.reports
  add column if not exists prescription_done boolean not null default false;

alter table public.reports
  add column if not exists collection_year integer;

alter table public.reports
  add column if not exists collection_month integer check (collection_month between 1 and 12);

alter table public.reports
  add column if not exists branch_name text;

alter table public.reports
  add column if not exists success_case text;

alter table public.reports
  drop constraint if exists reports_product_check;

create index if not exists reports_report_date_idx on public.reports (report_date);
create index if not exists reports_owner_idx on public.reports (owner);
create index if not exists reports_collection_idx on public.reports (collection_year, collection_month);

create table if not exists public.report_logs (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('update', 'delete')),
  created_at bigint not null,
  actor text,
  report_id text,
  client text,
  before_data jsonb,
  after_data jsonb
);

create index if not exists report_logs_created_at_idx on public.report_logs (created_at desc);
create index if not exists report_logs_report_id_idx on public.report_logs (report_id);

create table if not exists public.daily_completions (
  id text primary key,
  report_date date not null,
  owner text not null,
  completed_at bigint not null,
  status text not null default 'done'
);

alter table public.daily_completions
  add column if not exists status text not null default 'done';

create unique index if not exists daily_completions_date_owner_uidx
on public.daily_completions (report_date, owner);

create index if not exists daily_completions_report_date_idx
on public.daily_completions (report_date);

create table if not exists public.team_calendar_days (
  id text primary key,
  calendar_date date not null unique,
  status text not null check (status in ('holiday', 'workday')),
  label text,
  created_at bigint not null,
  updated_at bigint not null
);

create unique index if not exists team_calendar_days_date_uidx
on public.team_calendar_days (calendar_date);

create index if not exists team_calendar_days_status_idx
on public.team_calendar_days (status);

create table if not exists public.exhibition_events (
  id text primary key,
  event_date date not null,
  title text not null,
  needed_count integer not null default 2 check (needed_count between 1 and 7),
  memo text,
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists exhibition_events_event_date_idx
on public.exhibition_events (event_date desc);

create table if not exists public.exhibition_event_days (
  id text primary key,
  event_id text not null references public.exhibition_events(id) on delete cascade,
  event_date date not null,
  needed_count integer not null default 2 check (needed_count between 1 and 7),
  created_at bigint not null,
  updated_at bigint not null
);

insert into public.exhibition_event_days (
  id, event_id, event_date, needed_count, created_at, updated_at
)
select
  e.id || '-' || to_char(e.event_date, 'YYYYMMDD'),
  e.id,
  e.event_date,
  e.needed_count,
  e.created_at,
  e.updated_at
from public.exhibition_events e
where not exists (
  select 1 from public.exhibition_event_days d where d.event_id = e.id
);

create unique index if not exists exhibition_event_days_event_date_uidx
on public.exhibition_event_days (event_id, event_date);

create index if not exists exhibition_event_days_event_id_idx
on public.exhibition_event_days (event_id);

create table if not exists public.exhibition_attendees (
  id text primary key,
  event_id text not null references public.exhibition_events(id) on delete cascade,
  event_day_id text,
  owner text not null,
  created_at bigint not null
);

alter table public.exhibition_attendees
  add column if not exists event_day_id text;

update public.exhibition_attendees a
set event_day_id = d.id
from public.exhibition_event_days d
where a.event_id = d.event_id
  and a.event_day_id is null;

drop index if exists exhibition_attendees_event_owner_uidx;

create unique index if not exists exhibition_attendees_day_owner_uidx
on public.exhibition_attendees (event_day_id, owner);

create index if not exists exhibition_attendees_owner_idx
on public.exhibition_attendees (owner);

select pg_notify('pgrst', 'reload schema');
